[versions]
agp = "8.5.1"
androidx-core = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-activity = "1.8.2"
androidx-fragment = "1.6.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
